export const ITEM_SELECTED = "ITEM_SELECTED";
export const FETCH_STORES_SUCCESS = "FETCH_STORES_SUCCESS";
export const FETCH_STORES_FAILED = "FETCH_STORES_FAILED";
export const FETCH_STORES_PENDING = "FETCH_STORES_PENDING";
export const SHOW_CONFIRMATION_MODAL = "SHOW_CONFIRMATION_MODAL";
